services:
  db:
    image: postgres:16-alpine
    container_name: sistema-db
    environment:
      POSTGRES_DB: sistema_administrativo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
